import { Scheme } from '../types/portalTypes';

export const MOCK_SCHEMES: Scheme[] = [
  {
    id: 'SCH-2026-PMEGP01',
    code: 'PMEGP-ALL-01',
    title: 'Prime Minister Employment Generation Programme (PMEGP)',
    department: 'Ministry of Micro, Small & Medium Enterprises (KVIC / Coir Board)',
    targetCategory: 'All',
    description: 'Credit-linked subsidy programme open to ALL citizens/entrepreneurs (General, SC, ST, OBC, EWS, Women, Ex-Servicemen). Capital subsidy ranges from 15% to 35% for manufacturing & service projects up to ₹50 Lakh.',
    maxLoanAmount: 5000000,
    maxProjectCost: 5000000,
    interestRate: 6.5,
    moratoriumMonths: 6,
    maxTenureYears: 7,
    maxFinancingPercent: 95,
    requiredDocuments: ['Aadhaar Card', 'Project Report / DPR', 'PAN Card', 'Educational Certificate', 'Bank Account Details'],
  },
  {
    id: 'SCH-2026-MUDRA02',
    code: 'MUDRA-KISHOR-02',
    title: 'Pradhan Mantri MUDRA Yojana (Kishor / Tarun)',
    department: 'SIDBI & Ministry of Finance',
    targetCategory: 'All',
    description: 'Collateral-free business loans open to ALL non-corporate, non-farm small/micro-enterprises up to ₹10 Lakh for business expansion, equipment purchase, and working capital.',
    maxLoanAmount: 1000000,
    maxProjectCost: 1100000,
    interestRate: 7.0,
    moratoriumMonths: 3,
    maxTenureYears: 5,
    maxFinancingPercent: 90,
    requiredDocuments: ['Aadhaar Card', 'Proof of Business Identity', 'PAN Card', 'Bank Statement (Last 6 Months)'],
  },
  {
    id: 'SCH-2026-STANDUP03',
    code: 'STANDUP-SCT-WOMEN-03',
    title: 'Stand-Up India Scheme for Women & SC/ST Entrepreneurs',
    department: 'Department of Financial Services (DFS)',
    targetCategory: 'Women & SC/ST',
    description: 'Bank loans between ₹10 Lakh and ₹1 Crore to at least one SC/ST borrower and at least one Woman borrower per bank branch for setting up greenfield enterprises.',
    maxLoanAmount: 10000000,
    maxProjectCost: 12000000,
    interestRate: 6.0,
    moratoriumMonths: 18,
    maxTenureYears: 7,
    maxFinancingPercent: 85,
    requiredDocuments: ['Aadhaar Card', 'SC/ST/Category Certificate (if applicable)', 'Detailed Project Report', 'Business Registration', 'Bank Details'],
  },
  {
    id: 'SCH-2026-MF04',
    code: 'NSFDC-MF-04',
    title: 'NSFDC Concessional Micro Finance Scheme',
    department: 'National Scheduled Castes Finance & Development Corp (MoSJE)',
    targetCategory: 'SC',
    description: 'Concessional micro-credit assistance up to ₹1.4 Lakh for micro-enterprises, tailoring, village trades, and small retail ventures at 5% p.a. interest rate.',
    maxLoanAmount: 140000,
    maxProjectCost: 150000,
    interestRate: 5.0,
    moratoriumMonths: 6,
    maxTenureYears: 3,
    maxFinancingPercent: 90,
    requiredDocuments: ['Aadhaar Card', 'Income Certificate (<= ₹3.0 Lakh)', 'SC Caste Certificate', 'Project Proposal', 'Bank Passbook'],
  },
  {
    id: 'SCH-2026-NBCFDC05',
    code: 'NBCFDC-TL-05',
    title: 'National OBC Term Loan & Micro Credit Scheme',
    department: 'National Backward Classes Finance & Development Corporation',
    targetCategory: 'OBC',
    description: 'Concessional financial loan support for viable income-generating business projects for Other Backward Classes (OBC) beneficiaries up to ₹15 Lakh.',
    maxLoanAmount: 1500000,
    maxProjectCost: 1700000,
    interestRate: 6.0,
    moratoriumMonths: 6,
    maxTenureYears: 5,
    maxFinancingPercent: 85,
    requiredDocuments: ['Aadhaar Card', 'OBC Caste Certificate', 'Income Certificate', 'Project Proposal', 'Bank Details'],
  },
  {
    id: 'SCH-2026-MSY06',
    code: 'MSY-WOMEN-06',
    title: 'Mahila Samriddhi Yojana (Women Empowerment)',
    department: 'MoSJE & State Channelizing Agencies',
    targetCategory: 'Women',
    description: 'Micro-credit financial assistance specifically tailored for women entrepreneurs across all eligible categories for small business ventures at 4% p.a. interest rate.',
    maxLoanAmount: 140000,
    maxProjectCost: 150000,
    interestRate: 4.0,
    moratoriumMonths: 6,
    maxTenureYears: 3,
    maxFinancingPercent: 95,
    requiredDocuments: ['Aadhaar Card', 'Income Certificate', 'Self-Declaration Form', 'Bank Details'],
  },
  {
    id: 'SCH-2026-VISHWAKARMA07',
    code: 'PM-VISHWAKARMA-07',
    title: 'PM Vishwakarma Scheme for Artisans & Craftsmen',
    department: 'Ministry of MSME & Ministry of Skill Development',
    targetCategory: 'Artisan',
    description: 'End-to-end support for traditional artisans and craftspeople (carpenters, blacksmiths, goldsmiths, potters, tailors, weavers) with collateral-free credit up to ₹3 Lakh at 5% interest.',
    maxLoanAmount: 300000,
    maxProjectCost: 320000,
    interestRate: 5.0,
    moratoriumMonths: 6,
    maxTenureYears: 4,
    maxFinancingPercent: 95,
    requiredDocuments: ['Aadhaar Card', 'Artisan Registration / Skill Verification', 'Bank Passbook'],
  },
  {
    id: 'SCH-2026-NMDFC08',
    code: 'NMDFC-TERM-08',
    title: 'NMDFC Term Loan Scheme for Minorities',
    department: 'National Minorities Development & Finance Corporation',
    targetCategory: 'Minority',
    description: 'Concessional term loans for minority community entrepreneurs (Muslims, Christians, Sikhs, Buddhists, Parsis, Jains) for income-generating activities up to ₹20 Lakh.',
    maxLoanAmount: 2000000,
    maxProjectCost: 2200000,
    interestRate: 6.0,
    moratoriumMonths: 6,
    maxTenureYears: 5,
    maxFinancingPercent: 90,
    requiredDocuments: ['Aadhaar Card', 'Minority Self-Declaration', 'Income Certificate', 'Project Report', 'Bank Details'],
  },
  {
    id: 'SCH-2026-EDU09',
    code: 'NATIONAL-EDU-09',
    title: 'National Educational Loan Scheme for Higher Studies',
    department: 'Ministry of Education & MoSJE',
    targetCategory: 'All',
    description: 'Concessional educational loan scheme providing funding up to ₹20 Lakh for higher professional education in India and abroad for all eligible students.',
    maxLoanAmount: 2000000,
    maxProjectCost: 2200000,
    interestRate: 4.5,
    moratoriumMonths: 12,
    maxTenureYears: 7,
    maxFinancingPercent: 90,
    requiredDocuments: ['Aadhaar Card', 'Admission Letter', '10th & 12th Marksheets', 'Income Certificate', 'Bank Details'],
  }
];
